kind: pipeline
type: kubernetes
name: GestionCommandes

platform:
  os: linux
  arch: amd64

steps:
- name: docker build
  image: plugins/docker
  settings:
    registry: registry.germainleignel.com
    repo: registry.germainleignel.com/paye-ton-kawa/gestionCommandes
    tags: latest
    username: 
      from_secret: harbor_username
    password: 
      from_secret: harbor_password
    dockerfile: Dockerfile
    context: .
    insecure: true
    debug: true
    ulimits:
    nproc: 65535
    nofile:
      soft: 200000
      hard: 200000

trigger:
  branch:
    - main