kind: pipeline
type: kubernetes
name: GestionCommandes

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang
    commands:
      - go test
      - go build

trigger:
  branch:
    - main
