kind: pipeline
type: kubernetes
name: GestionCommandes

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang
  commands:
  - go test

- name: sonarqube
  image: sonarsource/sonar-scanner-cli
  commands:
  - sonar-scanner \
      -Dsonar.projectKey=MSPR-PayeTonKawa_gestionCommandes_ec4f6a4f-4e6f-4a92-845b-d61ec288fa5a \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonar.germainleignel.com \
      -Dsonar.login=${SONAR_TOKEN}

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
    repo: registry.germainleignel.com/paye-ton-kawa/gestion-commandes
    registry: registry.germainleignel.com

trigger:
  branch:
  - main
