kind: pipeline
type: kubernetes
name: GestionCommandes

platform:
  os: linux
  arch: amd64

steps:
  - name: sonarqube
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - sonar-scanner -Dsonar.projectKey=MSPR-PayeTonKawa_gestionCommandes_909bdf9b-3c96-4895-9a16-4f87c5490a8f -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

  - name: test
    image: golang
    commands:
      - go test

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      repo: registry.germainleignel.com/paye-ton-kawa/gestion-commandes
      registry: registry.germainleignel.com

  - name: deploy
    image: bitnami/kubectl:latest
    environment:
      KUBECONFIG: /root/.kube/config
    volumes:
      - name: kubeconfig
        path: /root/.kube
    commands:
      - mkdir -p /root/.kube
      - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
      - kubectl apply -f ./kubernetes/prod
      - kubectl rollout restart deployment $COMMANDES_DEPLOYMENT


  - name: msg status
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: "{{#success build.status}}✅{{else}}❌{{/success}}  Repository `[{{repo.name}}/{{commit.branch}}]` triggered by event `[{{uppercase build.event}}]` for build.\n    - Commit [[{{commit.sha}}]({{commit.link}})]\n    - Author `[{{commit.author}} / {{commit.email}}]`\n    - Message: {{commit.message}}    - Drone build [[#{{build.number}}]({{build.link}})] reported `[{{uppercase build.status}}]` at `[{{datetime build.finished \"2006.01.02 15:04\" \"\"}}]`\n"
      when:
        status: [success, failure, changed]

trigger:
  branch:
    - main
