kind: pipeline
type: kubernetes
name: GestionCommandes

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      repo: registry.germainleignel.com/paye-ton-kawa/gestionCommandes
      registry: registry.germainleignel.com

trigger:
  branch:
    - main
