openapi: 3.0.0
info:
  title: Order Management API
  description: API for managing orders within an e-commerce system.
  version: "1.0"
servers:
  - url: 'https://api.yourdomain.com/v1'
    description: Production server

paths:
  /orders:
    get:
      summary: List all orders
      operationId: listOrders
      tags:
        - Orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderArray'
    post:
      summary: Create a new order
      operationId: createOrder
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /orders/{orderId}:
    get:
      summary: Get an order by ID
      operationId: getOrder
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    put:
      summary: Update an order
      operationId: updateOrder
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    delete:
      summary: Delete an order
      operationId: deleteOrder
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order deleted

components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
          example: '12345'
        customerName:
          type: string
          example: 'John Doe'
        orderDate:
          type: string
          format: date-time
          example: '2021-06-23T18:25:43.511Z'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        status:
          type: string
          example: 'Shipped'
        total:
          type: number
          format: float
          example: 150.50
    OrderItem:
      type: object
      properties:
        productId:
          type: string
          example: 'P100'
        quantity:
          type: integer
          example: 2
        price:
          type: number
          format: float
          example: 25.50
    OrderArray:
      type: array
      items:
        $ref: '#/components/schemas/Order'
