name: gestion-commandes
services:
  app:
    build: .
    ports:
      - 3001:8080
    depends_on:
      - db-commandes
    env_file:
      - .env

  db-commandes:
    container_name: db-commandes
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
