name: gestion-commandes
services:
  gestion-commandes:
    container_name: gestion-commandes
    build: ../gestionCommandes
    depends_on:
      - db-commandes
    env_file:
      - ../gestionCommandes/.env
    networks:
      - payetonkawa-n

  db-commandes:
    container_name: db-commandes
    image: postgres
    env_file:
      - ../gestionCommandes/.env
    volumes:
      - db-commandes-data:/var/lib/postgresql/data
    networks:
      - payetonkawa-n

volumes:
  db-commandes-data:

networks:
  payetonkawa-n:
    external: true