apiVersion: v1
kind: Service
metadata:
  name: gestion-commandes-service
  namespace: payetonkawa-prod
spec:
  selector:
    app: gestion-commandes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080