apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: payetonkawa-certificate
  namespace: payetonkawa-prod  # Adjust the namespace to where your service is deployed
spec:
  secretName: payetonkawa-tls
  issuerRef:
    name: letsencrypt-prod  # Change to letsencrypt-staging if you're not ready for production
    kind: ClusterIssuer
  dnsNames:
  - api.payetonkawa.germainleignel.com

